spring:
  application:
    name: ServerDiscoveryProject
  security:
    user:
      name: ${EUREKA_USERNAME}
      password: ${EUREKA_PASSWORD}
server:
  port: 8761
  tomcat:
    max-connections: 50
    threads:
      max: 50
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: false

